### PR TITLE
Display donor's address in User table

### PR DESCRIPTION
**Pull request by seanpdoyle**
screen shot 2016-04-21 at 6 10 45 pm
https://trello.com/c/B7amg0Ix

When viewing the list of donors, include their address and zipcode in
their row.

### CODE REVIEW

**Comment by teoljungberg** [comment]
Is there a feature spec that we could write to verify the change?

**Comment by seanpdoyle** [comment]
@teoljungberg no, there isn't. I was hoping the fact that nothing broke would be enough.

Instead, how do you feel about a view spec for each of these partials?

**Comment by teoljungberg** [comment]
I rely more on feature specs than view specs. I more want to see a test to verify that this was added, so I would be fine with a view spec for that.

**Comment by seanpdoyle** [comment]
@teoljungberg I've added some view specs. This is ready for another look

**Pull request merged**
